### PR TITLE
Update to Sinatra 2 which use Rack 2

### PR DESCRIPTION
**Pull request by GCorbel**
Update Sinatra to be compatible with Rails 5

### CODE REVIEW

**Review by jarthod — APPROVED** [review]
Ok nice ;)

**Comment by jarthod** [comment]
Mm actually no can't we just put `> 1.3` ? we don't need to lock the new version on 2.0 we'd better make it permissive if it's compatible this way we can update the gem right away and support rails 4 and 5

**Comment by GCorbel** [comment]
You're right. I did the change.

**Comment by jarthod** [comment]
Great, thanks. I think you can merge now

**Comment by jarthod** [comment]
Please update the version number too

**Comment by GCorbel** [comment]
Done.

**Pull request merged**
